# Generated by Django 4.2 on 2024-01-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(null=True, upload_to='media/'),
        ),
    ]
